### ISSUE TITLE
Can't define interfaces, extending the other ones

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#313]
The following test doesn't work:

```java
public void testInterface() throws Exception {
    String classText = "package test;\n"
            + "public interface TTest extends Runnable { }";

    Class aClass = (Class) new Interpreter().eval(classText);
    Object o = aClass.newInstance();
    assertTrue(o instanceof Runnable);
}
```

With the error:

```
C:\j2sdk1.4.2_04\bin\java -ea
-Xbootclasspath/p:lib\aurora-support.jar
-Didea.launcher.port=7534
-Didea.launcher.library=C:\IDEA\bin\breakgen.dll
-Dfile.encoding=windows-1251 -classpath
C:\j2sdk1.4.2_04\jre\lib\charsets.jar;C:\j2sdk1.4.2_04\jre\lib\jce.jar;C:\j2sdk1.4.2_04\jre\lib\jsse.jar;C:\j2sdk1.4.2_04\jre\lib\plugin.jar;C:\j2sdk1.4.2_04\jre\lib\rt.jar;C:\j2sdk1.4.2_04\jre\lib\sunrsasign.jar;C:\j2sdk1.4.2_04\jre\lib\ext\dnsns.jar;C:\j2sdk1.4.2_04\jre\lib\ext\ldapsec.jar;C:\j2sdk1.4.2_04\jre\lib\ext\localedata.jar;C:\j2sdk1.4.2_04\jre\lib\ext\sunjce_provider.jar;C:\Work\Fabrique\fabrique-ide\classes\test;C:\Work\Fabrique\fabrique-ide\classes\main;C:\Work\Fabrique\fabrique-framework\classes\main;C:\Work\Fabrique\fabrique-framework\resources;C:\Work\Fabrique\lib\ant-1.6.1.jar;C:\Work\Fabrique\lib\ant-launcher-1.6.1.jar;C:\Work\Fabrique\lib\ejb-2.1.jar;C:\Work\Fabrique\lib\servletapi-2.3.jar;C:\Work\Fabrique\lib\mockobjects-jdk1.4-j2ee1.3-0.09.jar;C:\Work\Fabrique\lib\mockobjects-core-0.09.jar;C:\Work\Fabrique\lib\junit-3.8.1.jar;C:\Work\Fabrique\lib\qname.jar;C:\Work\Fabrique\lib\commons-logging-1.0.2.jar;C:\Work\Fabrique\lib\jdom-1.0beta9.jar;C:\Work\Fabrique\lib\jta-1.0.1.jar;C:\Work\Fabrique\lib\log4j-1.2.7.jar;C:\Work\Fabrique\lib\xdoclet-1.2.jar;C:\Work\Fabrique\lib\xjavadoc-1.0.jar;C:\Work\Fabrique\fabrique-ide\resources;C:\Work\Fabrique\lib\aurora-SNAPSHOT.jar;C:\Work\Fabrique\lib\trove4j.jar;C:\Work\Fabrique\lib\alloy.jar;C:\Work\Fabrique\lib\instantj-1.6.jar;C:\Work\Fabrique\lib\yjp-controller-api-redist.jar;C:\Work\Fabrique\lib\tools.jar;C:\Work\Fabrique\lib\wsdl4j.jar;C:\Work\Fabrique\lib\wsif.jar;C:\Work\Fabrique\lib\jniwrap-1.2-20030717.jar;C:\Work\Fabrique\lib\velocity-1.3.jar;C:\Work\Fabrique\lib\xmlrpc-1.1.jar;C:\Work\Fabrique\lib\marathon.jar;C:\Work\Fabrique\fabrique-activeLibraries\dataTypes\classes\main;C:\Work\Fabrique\fabrique-activeLibraries\dataTypes\resources;C:\Work\Fabrique\fabrique-ide\testResources;C:\Work\Fabrique\fabrique-framework\classes\test;C:\Work\Fabrique\fabrique-ide\sharedTestResources;C:\Work\Fabrique\fabrique-activeLibraries\controls\classes\main;C:\Work\Fabrique\fabrique-activeLibraries\controls\resources;C:\Work\Fabrique\fabrique-activeLibraries\controls\classes\test;C:\Work\Fabrique\fabrique-activeLibraries\controls\classes\design;C:\Work\Fabrique\fabrique-activeLibraries\webControlsDesignMode\classes\main;C:\Work\Fabrique\fabrique-activeLibraries\webControlsDesignMode\resources;C:\Work\Fabrique\fabrique-activeLibraries\indexPage\classes\main;C:\Work\Fabrique\fabrique-activeLibraries\indexPage\resources;C:\Work\Fabrique\lib\bsh-2.0b1.jar;C:\IDEA\lib\idea_rt.jar
com.intellij.rt.execution.application.AppMain
com.intellij.rt.execution.junit2.JUnitStarter
-ideVersion5
jetbrains.fabrique.tools.compiler.BeanshellTest
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at bsh.Reflect.invokeOnMethod(Unknown Source)
at bsh.Reflect.invokeObjectMethod(Unknown Source)
at bsh.BshClassManager.defineClass(Unknown Source)
at bsh.ClassGeneratorImpl.generateClassImpl(Unknown
Source)
at bsh.ClassGeneratorImpl.generateClass(Unknown Source)
at bsh.BSHClassDeclaration.eval(Unknown Source)
at bsh.Interpreter.eval(Unknown Source)
at bsh.Interpreter.eval(Unknown Source)
at bsh.Interpreter.eval(Unknown Source)
at
jetbrains.fabrique.tools.compiler.BeanshellTest.testInterface(BeanshellTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at junit.framework.TestCase.runTest(TestCase.java:154)
at junit.framework.TestCase.runBare(TestCase.java:127)
at
junit.framework.TestResult$1.protect(TestResult.java:106)
at
junit.framework.TestResult.runProtected(TestResult.java:124)
at junit.framework.TestResult.run(TestResult.java:109)
at junit.framework.TestCase.run(TestCase.java:118)
at junit.framework.TestSuite.runTest(TestSuite.java:208)
at junit.framework.TestSuite.run(TestSuite.java:203)
at junit.textui.TestRunner.doRun(TestRunner.java:116)
at
com.intellij.rt.execution.junit2.IdeaJUnitAgent.doRun(IdeaJUnitAgent.java:57)
at junit.textui.TestRunner.start(TestRunner.java:172)
at
com.intellij.rt.execution.junit.TextTestRunner2.startRunnerWithArgs(TextTestRunner2.java:23)
at
com.intellij.rt.execution.junit2.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:97)
at
com.intellij.rt.execution.junit2.JUnitStarter.main(JUnitStarter.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at
com.intellij.rt.execution.application.AppMain.main(AppMain.java:78)
Caused by: java.lang.ClassFormatError: Interfaces must
have java.lang.Object as superclass
at java.lang.ClassLoader.defineClass0(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:537)
at java.lang.ClassLoader.defineClass(ClassLoader.java:448)
... 37 more
bsh.InterpreterError: Unable to define class:
java.lang.reflect.InvocationTargetException
at bsh.BshClassManager.defineClass(Unknown Source)
at bsh.ClassGeneratorImpl.generateClassImpl(Unknown
Source)
at bsh.ClassGeneratorImpl.generateClass(Unknown Source)
at bsh.BSHClassDeclaration.eval(Unknown Source)
at bsh.Interpreter.eval(Unknown Source)
at bsh.Interpreter.eval(Unknown Source)
at bsh.Interpreter.eval(Unknown Source)
at
jetbrains.fabrique.tools.compiler.BeanshellTest.testInterface(BeanshellTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at junit.framework.TestCase.runTest(TestCase.java:154)
at junit.framework.TestCase.runBare(TestCase.java:127)
at
junit.framework.TestResult$1.protect(TestResult.java:106)
at
junit.framework.TestResult.runProtected(TestResult.java:124)
at junit.framework.TestResult.run(TestResult.java:109)
at junit.framework.TestCase.run(TestCase.java:118)
at junit.framework.TestSuite.runTest(TestSuite.java:208)
at junit.framework.TestSuite.run(TestSuite.java:203)
at junit.textui.TestRunner.doRun(TestRunner.java:116)
at
com.intellij.rt.execution.junit2.IdeaJUnitAgent.doRun(IdeaJUnitAgent.java:57)
at junit.textui.TestRunner.start(TestRunner.java:172)
at
com.intellij.rt.execution.junit.TextTestRunner2.startRunnerWithArgs(TextTestRunner2.java:23)
at
com.intellij.rt.execution.junit2.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:97)
at
com.intellij.rt.execution.junit2.JUnitStarter.main(JUnitStarter.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at
com.intellij.rt.execution.application.AppMain.main(AppMain.java:78)

Sourced file: inline evaluation of: ``package test;
public interface TTest extends Runnable { };'' internal
Error: Unable to define class:
java.lang.reflect.InvocationTargetException : at Line:
2 : in file: inline evaluation of: ``package test;
public interface TTest extends Runnable { };'' : public
interface TTest extends Runnable {

at bsh.Interpreter.eval(Unknown Source)
at bsh.Interpreter.eval(Unknown Source)
at bsh.Interpreter.eval(Unknown Source)
at
jetbrains.fabrique.tools.compiler.BeanshellTest.testInterface(BeanshellTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at
com.intellij.rt.execution.junit2.JUnitStarter.main(JUnitStarter.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at
com.intellij.rt.execution.application.AppMain.main(AppMain.java:78)

Process finished with exit code -1

```

Reported by: mm_aa

Original Ticket: "beanshell/bugs/175":https://sourceforge.net/p/beanshell/bugs/175

**Comment by opeongo** [comment]
It looks like this might not be a bug.  In the sample script that was provided there is an attempt to instantiate an interface.  How would/should BeanShell handle this?

```java
public void testInterface() throws Exception {
String classText = "package test;\n" +
"public interface TTest extends Runnable { }";

Class aClass = (Class) new
Interpreter().eval(classText);
Object o = aClass.newInstance();
assertTrue(o instanceof Runnable);
}
```

As I was looking in to it I noticed that the javap output was not correct for the aClass variable:
```
Class interface test.TTest extends null
public static final bsh.This test.TTest._bshStaticTTest
public static final java.lang.String test.TTest.UUID
```

javap needs to be taught how to print interfaces.  The output of aClass.getInterfaces() has Runnable, so it looks like the interface got assembled correctly:
```
interface java.lang.Runnable
interface bsh.GeneratedClass
```

**Comment by nickl-** [comment]
> It looks like this might not be a bug. In the sample script that was provided there is an attempt to instantiate an interface. How would/should BeanShell handle this?

@opeongo Ahh yes looks like this issue was from before we could create interfaces.

> javap needs to be taught how to print interfaces. The output of aClass.getInterfaces() has Runnable, so it looks like the interface got assembled correctly:

I've been meaning to rewrite javap yes... it should use the `StringUtil` functions and we need to check capabilities of `interface` as well as `enum`

**Comment by jimjag** [comment]
Works correctly with BeanShell 3.0.0-SNAPSHOT.841

```
bsh % public void testInterface() throws Exception {
    String classText = "package test;\n"
            + "public interface TTest extends Runnable { }";

    Class aClass = (Class) new Interpreter().eval(classText);
    Object o = aClass.newInstance();
    assertTrue(o instanceof Runnable);
}
--> void
```
