### ISSUE TITLE
anonymous classes works not always

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#334]
Hello\!
I hava a big problem wenn i use anonymous classes.
This small skript should demonstrates the error:
```java
String s = "import javax.swing.*;\n" +
    "JLabel l = new JLabel() {};\n" + // this works
    "if (l instanceof JLabel) {\n" +
        "JLabel ll = new JLabel() {};\n"+ // this not...
    "}";
new bsh.Interpreter().eval(s);
```
Maybe i've done somethring worong...but i don't know what...so i 
think it could be an error.

My Java version is: 1.4.2\_01-b06.
Bsh version:
-rwxr-xr-x    1 NvK      users        275K 2004-11-25 10:47 bsh-2.0b2.
jar
sum bsh-2.0b2.jar: 49686   275

/\*
The Error is:
global/BlockNameSpace$2 \(Illegal Field name "\_bshStaticglobal/
BlockNameSpace$2"\)
java.lang.ClassFormatError: global/BlockNameSpace$2 \(Illegal 
Field name "\_bshStaticglobal/BlockNameSpace$2"\)
at java.lang.ClassLoader.defineClass0\(Native Method\)
at java.lang.ClassLoader.defineClass\(ClassLoader.java:
537\)
at java.lang.ClassLoader.defineClass\(ClassLoader.java:
448\)
at bsh.classpath.DiscreteFilesClassLoader.
findClass\(Unknown Source\)
at bsh.classpath.BshClassLoader.loadClass\(Unknown 
Source\)
at java.lang.ClassLoader.loadClass\(ClassLoader.java:235\)
at bsh.classpath.ClassManagerImpl.classForName\(Unknown 
Source\)
at bsh.classpath.ClassManagerImpl.defineClass\(Unknown 
Source\)
at bsh.ClassGeneratorImpl.generateClassImpl\(Unknown 
Source\)
at bsh.ClassGeneratorImpl.generateClass\(Unknown Source\)
at bsh.BSHAllocationExpression.
constructWithClassBody\(Unknown Source\)
at bsh.BSHAllocationExpression.objectAllocation\(Unknown 
Source\)
at bsh.BSHAllocationExpression.eval\(Unknown Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown Source\)
at bsh.BSHVariableDeclarator.eval\(Unknown Source\)
at bsh.BSHTypedVariableDeclaration.eval\(Unknown 
Source\)
at bsh.BSHBlock.evalBlock\(Unknown Source\)
at bsh.BSHBlock.eval\(Unknown Source\)
at bsh.BSHBlock.eval\(Unknown Source\)
at bsh.BSHIfStatement.eval\(Unknown Source\)
at bsh.Interpreter.eval\(Unknown Source\)
at bsh.Interpreter.eval\(Unknown Source\)
at bsh.Interpreter.eval\(Unknown Source\)
at dataflex.Frame1.initGUI\(Frame1.java:421\)

\*/ 

Reported by: datacon

Original Ticket: "beanshell/bugs/196":https://sourceforge.net/p/beanshell/bugs/196

**Comment by nickl-** [comment]
Can reproduce:

```java
bsh % import javax.swing.*;
--> void
bsh % JLabel l = new JLabel() {};
--> $7 = global$anon1[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER] :global$anon1
bsh % if (l instanceof JLabel) {
    JLabel ll = new JLabel() {};
}

Exception in thread "main" java.lang.NoClassDefFoundError: IllegalName: global/BlockNameSpace$anon2
at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:887)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1011)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:875)
at bsh.classpath.DiscreteFilesClassLoader.findClass(DiscreteFilesClassLoader.java:81)
at bsh.classpath.BshClassLoader.loadClass(BshClassLoader.java:107)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
at bsh.classpath.ClassManagerImpl.classForName(ClassManagerImpl.java:172)
at bsh.classpath.ClassManagerImpl.defineClass(ClassManagerImpl.java:603)
at bsh.ClassGenerator.generateClassImpl(ClassGenerator.java:124)
at bsh.ClassGenerator.generateClass(ClassGenerator.java:55)
at bsh.BSHAllocationExpression.constructWithClassBody(BSHAllocationExpression.java:196)
at bsh.BSHAllocationExpression.objectAllocation(BSHAllocationExpression.java:110)
at bsh.BSHAllocationExpression.eval(BSHAllocationExpression.java:63)
at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:124)
at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:67)
at bsh.BSHAssignment.eval(BSHAssignment.java:40)
at bsh.BSHVariableDeclarator.eval(BSHVariableDeclarator.java:80)
at bsh.BSHTypedVariableDeclaration.eval(BSHTypedVariableDeclaration.java:82)
at bsh.BSHBlock.evalBlock(BSHBlock.java:145)
at bsh.BSHBlock.eval(BSHBlock.java:89)
at bsh.BSHBlock.eval(BSHBlock.java:55)
at bsh.BSHIfStatement.eval(BSHIfStatement.java:42)
at bsh.Interpreter.run(Interpreter.java:509)
at bsh.Interpreter.main(Interpreter.java:452)
```

**Comment by nickl-** [comment]
Resolved:
```java
BeanShell 3.0.0-SNAPSHOT.3764
bsh % {{{{ test = new Object() {}; }}}}
--> $0 = global_BlockNameSpace7_BlockNameSpace8_BlockNameSpace9_BlockNameSpace10$anon1@5ba23b66 :global_BlockNameSpace7_BlockNameSpace8_BlockNameSpace9_BlockNameSpace10$anon1
```
