### ISSUE TITLE
Implement anonymous inner class scope

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#420]
BSH rejects a final modifier when applied to a method argument.

The attached code gives:

java -cp bsh.jar bsh.Interpreter ScopeBug.java
Evaluation Error: Parse error at line 7, column 14.  Encountered: final

javac compiles and executes it just fine.

\- Godmar

Reported by: gback

Original Ticket: "beanshell/bugs/282":https://sourceforge.net/p/beanshell/bugs/282

**Comment by opeongo** [comment]
Original test script
[ScopeBug.java.txt](https://github.com/beanshell/beanshell/files/2303396/ScopeBug.java.txt)

**Comment by opeongo** [comment]
It appears that the parsing problem has been corrected, but there is a problem with the variable lookup.  Running the script yields the following output:
```text
BeanShell 2.1.0-SNAPSHOT - by Pat Niemeyer (pat@pat.net)
bsh % source("ScopeBug.java");
--> $0 = class ScopeBug :Class
bsh % ScopeBug.main(new String[0]);
// Error: Target Exception: Method Invocation ScopeBug.main : at Line: 2 : in file: <unknown file> : ScopeBug .main ( new String [ 0 ] )
Caused by: java.lang.StackOverflowError
        at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.containsKey(Unknown Source)
        at bsh.util.ReferenceCache.get(ReferenceCache.java:82)
        at bsh.Reflect.resolveExpectedJavaField(Reflect.java:278)
        at bsh.Reflect.getFieldValue(Reflect.java:217)
        at bsh.Reflect.getStaticFieldValue(Reflect.java:131)
        at bsh.Reflect.getClassStaticThis(Reflect.java:730)
        at bsh.Reflect.getThisNS(Reflect.java:757)
        at bsh.Reflect.getFieldValue(Reflect.java:220)
        at bsh.Reflect.getStaticFieldValue(Reflect.java:131)
        at bsh.Reflect.getClassStaticThis(Reflect.java:730)
        at bsh.Reflect.getThisNS(Reflect.java:757)
        at bsh.Reflect.getFieldValue(Reflect.java:220)
        at bsh.Reflect.getStaticFieldValue(Reflect.java:131)
        at bsh.Reflect.getClassStaticThis(Reflect.java:730)
        at bsh.Reflect.getThisNS(Reflect.java:757)
        at bsh.Reflect.getFieldValue(Reflect.java:220)
        at bsh.Reflect.getStaticFieldValue(Reflect.java:131)
        at bsh.Reflect.getClassStaticThis(Reflect.java:730)
        at bsh.Reflect.getThisNS(Reflect.java:757)
        ... turtles all the way down 
```

**Comment by jimjag** [comment]
Slightly better with BeanShell 3.0.0-SNAPSHOT.841

```
       ...
        at bsh.Reflect.getStaticFieldValue(Reflect.java:131)
        at bsh.Reflect.getClassStaticThis(Reflect.java:897)
        at bsh.Reflect.getThisNS(Reflect.java:924)
        at bsh.Reflect.getFieldValue(Reflect.java:220)
        at bsh.Reflect.getObjectFieldValue(Reflect.java:148)
        at bsh.Reflect.getClassInstanceThis(Reflect.java:910)
        at bsh.Reflect.getThisNS(Reflect.java:943)
        at bsh.Reflect.invokeObjectMethod(Reflect.java:101)
        at bsh.Name.invokeMethod(Name.java:854)
        at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:72)
        at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:124)
        at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:67)
        at bsh.BSHAssignment.eval(BSHAssignment.java:40)
        at bsh.BSHBlock.evalBlock(BSHBlock.java:145)
        at bsh.BSHBlock.eval(BSHBlock.java:89)
        at bsh.BshMethod.invokeImpl(BshMethod.java:451)
        at bsh.BshMethod.invoke(BshMethod.java:297)
        at bsh.BshMethod.invoke(BshMethod.java:226)
        at bsh.This.invokeMethod(This.java:390)
        at bsh.This.invokeMethod(This.java:316)
        at ScopeBug.main(Unknown Source)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:509)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:572)
        at bsh.Invocable.invokeTarget(Invocable.java:205)
        at bsh.Invocable.invoke(Invocable.java:223)
        at bsh.Reflect.invokeStaticMethod(Reflect.java:126)
        at bsh.Name.invokeMethod(Name.java:869)
        at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:72)
        at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:124)
        at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:67)
        at bsh.BSHAssignment.eval(BSHAssignment.java:40)
        at bsh.Interpreter.run(Interpreter.java:509)
        at bsh.Interpreter.main(Interpreter.java:452)
bsh %
```

**Comment by nickl-** [comment]
Jshell also struggles with this:

```java
jshell> ScopeBug.main(new String[0]);
|  attempted to use class ScopeBug which cannot be instantiated or its methods invoked until variable s is declared
```

**Comment by nickl-** [comment]
Modified the test script and the final doesn't do anything, s is in scope of the anonymous inner class.

```java
public class ScopeBug
{
    I cb;
    String s;
    ScopeBug(String s) { set(s); }
    void set(String s) {
        this.s = "this.s="+s;
        cb = new I() {
            public void run() {
                System.out.println(ScopeBug.this.s + " " + s);
            }
        };
    }
    public static void main(String []av) {
        ScopeBug b = new ScopeBug("a");
        b.cb.run();
        b.set("b");
        b.cb.run();
    }
}
```

I have no idea how we will implement this because there is no namespace for a class like this.

**Comment by nickl-** [comment]
Changed from bug to feature request, anonymous inner class scope not implemented.

**Comment by nickl-** [comment]
parent #660

**Comment by nickl-** [comment]
Seems to be resolved now using test code from https://github.com/beanshell/beanshell/issues/420#issuecomment-1334651905

output:
```java
BeanShell 3.0.0-SNAPSHOT.2931
bsh % ScopeBug.main({""});
this.s=a a
this.s=b b
--> void
```

Closed: resolved
