### ISSUE TITLE
Variable disappears from scope after try-catch

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#447]
I'm using beanshell \(2.0b5\) from a Java program thanks to the javax.script API.
After I moved from Java 1.5.0\_06 to 1.5.0\_13 \(I compiled the scripting api with Java 5\) I started to experience the following, reproducible bug.
Basically after a try-catch block, a variable defined before the block is no longer accessible. The stack trace says: 

```java
javax.script.ScriptException: Sourced file: eval stream : Undefined argument: a : at Line: 10 : in file: eval stream : ( a )
in eval stream at line number 10
at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:92)
at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:52)
at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:232)
at TestBeanshellBug.evaluate(TestBeanshellBug.java:27)
at TestBeanshellBug.main(TestBeanshellBug.java:40)
```

Following a test case to reproduce the bug.

Here the beanshell file:

```java
String a;

try {
    a = "foobar";
} catch (Exception e) {
    e.printStackTrace();
}

print(a);
```

This is the Java file:

```java
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

public class TestBeanshellBug {

    private static ScriptEngineManager scriptManager;
    private static ScriptEngine engine;

    static {
        scriptManager = new ScriptEngineManager();
        engine = scriptManager.getEngineByName("beanshell");
    }

    public void evaluate(String src) throws FileNotFoundException {

        Reader reader = new FileReader(src);
        try {
            engine.eval(reader);
        } catch(ScriptException e) {
            e.printStackTrace();
        }
    }

    /**
    * @param args
    * @throws FileNotFoundException
    */
    public static void main(String[] args) throws FileNotFoundException {
        TestBeanshellBug tbb = new TestBeanshellBug();
        tbb.evaluate(args[0]);
    }
}
```
There are two workarounds:

The first is to initialize the variable before the try-catch block:
```java
String a = "test";
try {
    a = "foobar";
} catch (Exception e) {
    e.printStackTrace();
}

print(a);
```

The second is not to use the try-catch at all.

Reported by: nobody

Original Ticket: "beanshell/bugs/309":https://sourceforge.net/p/beanshell/bugs/309

**Comment by nickl-** [comment]
```java
bsh % String a;
--> $1 = null :null
bsh % try {
    a = "foo";
} catch (e) {
    e.printStackTrace();
}

--> void
bsh % bsh % print(a);
foo
```

**Closed: works as expected**
