### ISSUE TITLE
division by zero error when multiplying 0 value

### ISSUE THREAD

**Issue by HaasJona** [beanshell/beanshell#522]
Multiplying zero with a number can lead to a division by zero error:

```
    @Test
    public void testZero() throws Exception {
        final PreparsedScript f = new PreparsedScript(
                "return 0 * 2;",
                _classLoader
        );
        assertEquals(0, f.invoke(Collections.emptyMap()));
    }
```

Expected result: Test passes.

Actual result:
```
bsh.TargetError: Failed operation: 0 "*" 2: Arithemetic Exception in binary op : at Line: 1 : in file: inline evaluation of: ``__execute() { return 0 * 2; } return this;'' : ; 

Called from method: __executeCaused by: java.lang.ArithmeticException: / by zero

	at bsh.UtilTargetError.toEvalError(UtilTargetError.java:62)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:106)
	at bsh.BSHAssignment.eval(BSHAssignment.java:42)
	at bsh.BSHReturnStatement.eval(BSHReturnStatement.java:42)
	at bsh.BSHBlock.evalBlock(BSHBlock.java:145)
	at bsh.BSHBlock.eval(BSHBlock.java:89)
	at bsh.BshMethod.invokeImpl(BshMethod.java:425)
	at bsh.BshMethod.invoke(BshMethod.java:297)
	at bsh.BshMethod.invoke(BshMethod.java:201)
	at bsh.PreparsedScript.invoke(PreparsedScript.java:77)
	at bsh.PreparsedScriptTest.testZero(PreparsedScriptTest.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ArithmeticException: / by zero
	at bsh.Operators.longBinaryOperation(Operators.java:256)
	at bsh.Operators.binaryOperationImpl(Operators.java:165)
	at bsh.Operators.binaryOperation(Operators.java:129)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:104)
	... 31 more
```

The cause seems to be the overflow check in

`bsh.Operators#longBinaryOperation`:
```

            case STAR:
                if ( Long.MAX_VALUE / lhs < rhs )
                    break;
                return lhs * rhs;
```

**Comment by nickl-** [comment]
Interesting... well spotted @HaasJona 

What we need is:

```java
case STAR:
                if ( lhs != 0 &&  Long.MAX_VALUE / lhs < rhs )
                    break;
                return lhs * rhs;
```

I believe there are at least 2 occurrences where this problem will occur.

tyvm for finding this fault.
