### ISSUE TITLE
What caused this ParseException?

### ISSUE THREAD

**Issue by liuqiyuan** [beanshell/beanshell#53]
When I try to eval the following code
```
String codeText = "import java.util.*;\n" +
                    "class Solution {\n" +
                    "    public int[] twoSum(int[] nums, int target) {\n" +
                    "        Map<Integer, Integer> map = new HashMap<>();\n" +
                    "        for (int i = 0; i < nums.length; i++) {\n" +
                    "            if (map.get(nums[i]) != null) {\n" +
                    "                return new int[]{map.get(nums[i]), i};\n" +
                    "            } else {\n" +
                    "                map.put(target - nums[i], i);\n" +
                    "            }\n" +
                    "        }\n" +
                    "        return new int[]{};\n" +
                    "    }\n" +
                    "}";
```
, I got error message: 

```
bsh.ParseException: In file: inline evaluation of: ``import java.util.*; class Solution {     public int[] twoSum(int[] nums, int tar . . . '' Encountered "," at line 4, column 26.

	at bsh.Parser.generateParseException(Parser.java:6106)
	at bsh.Parser.jj_consume_token(Parser.java:5977)
	at bsh.Parser.Statement(Parser.java:2699)
	at bsh.Parser.BlockStatement(Parser.java:2819)
	at bsh.Parser.Block(Parser.java:2779)
	at bsh.Parser.MethodDeclaration(Parser.java:389)
	at bsh.Parser.BlockStatement(Parser.java:2812)
	at bsh.Parser.Block(Parser.java:2779)
	at bsh.Parser.ClassDeclaration(Parser.java:311)
	at bsh.Parser.BlockStatement(Parser.java:2810)
	at bsh.Parser.Line(Parser.java:172)
	at bsh.Interpreter.Line(Interpreter.java:1011)
	at bsh.Interpreter.eval(Interpreter.java:641)
	at bsh.Interpreter.eval(Interpreter.java:750)
	at bsh.Interpreter.eval(Interpreter.java:739)
	at com.lianshuati.utils.CodeExecutor.executeCodeFromText(CodeExecutor.java:36)
	at com.lianshuati.utils.CodeExecutor.main(CodeExecutor.java:28)
```

Anyone know why couldn't the code go through?

**Comment by broneill** [comment]
BeanShell doesn't support generics.

**Comment by nickl-** [comment]
ParseException - does not understand the syntax

On line 4, which is: 
```
Map<Integer, Integer> map = new HashMap<>();\n" +
```

as @broneill said BeanShell cannot parse generics at this point.

Suggestion:

Remove the generics and try again.
