### ISSUE TITLE
Broken instantiation of remote console

### ISSUE THREAD

**Issue by harvv** [beanshell/beanshell#564]
there is an apparent regression on the master (3.0x) branch with respect to the remote java console capability.

This invocation successfully gets a remote console when using bsh-2.0b6:

jdk_8u152\bin\appletviewer.exe http://localhost:9091/remote/jconsole.html

However, when switching to 3.0.0-SNAPSHOT (built with current master branch), you get:

load: bsh.util.JRemoteApplet can't be instantiated.
load: bsh.util.JRemoteApplet can't be instantiated.java.lang.InstantiationException: bsh.util.JRemoteApplet

        at java.lang.Class.newInstance(Class.java:427)
        at sun.applet.AppletPanel.createApplet(AppletPanel.java:799)
        at sun.applet.AppletPanel.runLoader(AppletPanel.java:728)
        at sun.applet.AppletPanel.run(AppletPanel.java:378)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException: bsh.util.JRemoteApplet.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        ... 4 more
java.lang.InstantiationException: bsh.util.JRemoteApplet
        at java.lang.Class.newInstance(Class.java:427)
        at sun.applet.AppletPanel.createApplet(AppletPanel.java:799)
        at sun.applet.AppletPanel.runLoader(AppletPanel.java:728)
        at sun.applet.AppletPanel.run(AppletPanel.java:378)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException: bsh.util.JRemoteApplet.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        ... 4 more

Comparing JRemoteApplet in both versions, it seems the 3.0.0 version omits the init() method (and a no-arg constructor) that is apparently needed by the way the rest of the code creates one of these instances

**Comment by harvv** [comment]
Alternatively, perhaps there is now a separate class that handles the remote applet duties...in which case perhaps it's just the HTML "launcher" pages that need to be edited.

(with 3.0.0-SNAPSHOT, the index.html returned by http://localhost:<port>  in my browser gave the same URL reference of  "remote/jconsole.html" as the 2.0b6 version.  So perhaps either this URL needs to be different or the contents of jconsole.html need to change to load a different class)

**Comment by nickl-** [comment]
I need to look into this and get he specifics but my gut feeling is that it has something to do with applets being deprecated somewhere.

**Comment by opeongo** [comment]
Applets were deprecated.  They had too much of an attack surface and the browser manufacturers didn't want them.

The remote console capability was an interesting BeanShell utility and was a bit of a show off in it's day.  However, having a un-sandboxed interpreter that can read and modify the file system is a bit of a loaded gun to leave lying around.  I mean, what could go wrong?

The remote console is not a core BeanShell component.  If BeanShell were a more popular system then this type of tool would be in an add-on library where you could install it at your own risk.  As it is the remote interpreter part is trivially easy to get going as a CLI.  However, the GUI part is broken and needs a lot of work to get going again in a safe and responsible way.  Perhaps a better way going forward would be to replace the Applet part with a console terminal like [JQuery Terminal](https://terminal.jcubic.pl/).

For the purposes of moving forward swiftly towards a 3.0.0 release that this code should be removed.  If someone wants to code up a replacement then they can put it on to github.

**Comment by nickl-** [comment]
@opeongo thank you for looking into this.

Close: Applets deprecated
