### ISSUE TITLE
Static method xxx( java.lang.String ) not found in class'xxxxxx'

### ISSUE THREAD

**Issue by lliioollcn** [beanshell/beanshell#597]
in android;

code is
`//@QNScriptInfoStart
//@author:          lliiooll
//@name:           example
//@version:         0.0.1
//@label:           demo
//@decs:            example
//@QNScriptInfoEnd

import cn.lliiooll.QNClient;

public void onLoad(){
    QNClient.toast("successs!");
}`

in QNClient

`/**
     * send a toast
     *
     * @param msg
     */
    public static void toast(String msg) {
        //Utils.showToast(getApplication(), TOAST_TYPE_INFO, msg, Toasts.LENGTH_LONG);
        Toast.makeText(getApplication(), msg, Toast.LENGTH_LONG).show();
    }`

show
`2021-01-31 17:35:03.582 15607-15649/? E/QNdump: Sourced file: inline evaluation of: ``onLoad();'' : Error in method invocation: Static method toast( java.lang.String ) not found in class'cn.lliiooll.QNClient' : at Line: 13 : in file: inline evaluation of:  ``//@QNScriptInfoStart //@author:          lliiooll //@name:            example //@ve . . . '' : QNClient .toast ( "success!" ) 
    
    Called from method: onLoad : at Line: 1 : in file: inline evaluation of: ``onLoad();'' : onLoad ( ) 
        at bsh.BSHMethodInvocation.eval(Unknown Source:141)
        at bsh.BSHPrimaryExpression.eval(Unknown Source:38)
        at bsh.BSHPrimaryExpression.eval(Unknown Source:1)
        at bsh.BSHBlock.evalBlock(Unknown Source:50)
        at bsh.BSHBlock.eval(Unknown Source:32)
        at bsh.BshMethod.invokeImpl(Unknown Source:61)
        at bsh.BshMethod.invoke(Unknown Source:116)
        at bsh.BshMethod.invoke(Unknown Source:6)
        at bsh.Name.invokeLocalMethod(Unknown Source:40)
        at bsh.Name.invokeMethod(Unknown Source:32)
        at bsh.BSHMethodInvocation.eval(Unknown Source:57)
        at bsh.BSHPrimaryExpression.eval(Unknown Source:38)
        at bsh.BSHPrimaryExpression.eval(Unknown Source:1)
        at bsh.Interpreter.eval(Unknown Source:108)
        at bsh.Interpreter.eval(Unknown Source:40)
        at bsh.Interpreter.eval(Unknown Source:26)
        at cn.lliiooll.script.QNScriptFactory.initScript(QNScriptFactory.java:13)
        at nil.nadph.qnotified.script.QNScriptManager.init(QNScriptManager.java:7)
        at cn.lliiooll.hook.ScriptEventHook.initOnce(ScriptEventHook.java:1)
        at nil.nadph.qnotified.hook.CommonDelayableHook.init(CommonDelayableHook.java:2)
        at nil.nadph.qnotified.InjectDelayableHooks.step(InjectDelayableHooks.java:26)
        at nil.nadph.qnotified.MainHook$5.afterHookedMethod(MainHook.java:8)
        at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
        at me.apm$ʻ.ᐝ(SourceFile:324)
        at me.anc.a(SourceFile:273)
        at me.anc.a(SourceFile:202)
        at com.tencent.mobileqq.startup.step.LoadData_3545355312.doStep(Unknown Source:11)
        at com.tencent.mobileqq.startup.step.Step.step(P:126)
        at com.tencent.mobileqq.startup.step.Step.doStep(P:158)
        at com.tencent.mobileqq.startup.step.Step.step(P:126)
        at com.tencent.mobileqq.startup.director.StartupDirector.a(P:788)
        at com.tencent.mobileqq.startup.director.StartupDirector.handleMessage(P:801)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)`
but it does exist in QNClient

**Comment by opeongo** [comment]
It is difficult to understand what is going on here because there is not enough to go on.  Can you provide a [short self contained example](http://www.sscce.org/)?  That will help with the debugging process.

**Comment by nickl-** [comment]
**Closed: more information required**
