### ISSUE TITLE
Support for Java 9 (and beyond)

### ISSUE THREAD

**Issue by pejobo** [beanshell/beanshell#60]
The current way of resolving methods and fields does not work with Java 9. 
A simple code example, wich works up to Java 8, but not with 9 or 10:

```java
import java.net.URL;
url = new URL("https://github.com/beanshell");
urlConnection = url.openConnection();
stream = urlConnection.getInputStream();
```

If you run this with Java9 you'll get this exception (provide the jvm argument `--illegal-access=deny` if you only see a warning on the console):
```
bsh.EvalError: Error in method invocation: Cannot access method getInputStream() in 'class sun.net.www.protocol.https.HttpsURLConnectionImpl' :java.lang.IllegalAccessException: class bsh.Reflect cannot access class sun.net.www.protocol.https.HttpsURLConnectionImpl (in module java.base) because module java.base does not export sun.net.www.protocol.https to unnamed module @48503868 : at Line: 4 : in file: inline evaluation of: ``url = new URL("https://github.com/beanshell"); urlCon . . . '' : urlConnection .getInputStream ( ) 

Called from method: __execute
	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:77)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:47)
	at bsh.BSHAssignment.eval(BSHAssignment.java:77)
	at bsh.BSHBlock.evalBlock(BSHBlock.java:130)
	at bsh.BSHBlock.eval(BSHBlock.java:80)
	at bsh.BshMethod.invokeImpl(BshMethod.java:371)
	at bsh.BshMethod.invoke(BshMethod.java:267)
	at bsh.BshMethod.invoke(BshMethod.java:170)
	at bsh.PreparsedScript.invoke(PreparsedScript.java:66)
	at de.espirit.firstspirit.server.script.BeanshellScriptEngine$BeanshellExecutable.execute(BeanshellScriptEngine.java:100)
	at de.espirit.firstspirit.server.script.BeanshellScriptEngine$BeanshellExecutable.execute(BeanshellScriptEngine.java:111)
	at de.espirit.firstspirit.server.script.BeanshellScriptEngine$BeanshellExecutable.execute(BeanshellScriptEngine.java:84)
	at de.espirit.firstspirit.server.script.TestBeanshellScriptEngine.java_9_module_access(TestBeanshellScriptEngine.java:175)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: bsh.ReflectError: Cannot access method getInputStream() in 'class sun.net.www.protocol.https.HttpsURLConnectionImpl' :java.lang.IllegalAccessException: class bsh.Reflect cannot access class sun.net.www.protocol.https.HttpsURLConnectionImpl (in module java.base) because module java.base does not export sun.net.www.protocol.https to unnamed module @48503868
	at bsh.Reflect.invokeMethod(Reflect.java:174)
	at bsh.Reflect.invokeObjectMethod(Reflect.java:99)
	at bsh.Name.invokeMethod(Name.java:858)
	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:75)
	... 35 more
Caused by: java.lang.IllegalAccessException: class bsh.Reflect cannot access class sun.net.www.protocol.https.HttpsURLConnectionImpl (in module java.base) because module java.base does not export sun.net.www.protocol.https to unnamed module @48503868
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at bsh.Reflect.invokeMethod(Reflect.java:166)
	... 38 more
```
If you run this code with the jvm argument `--illegal-access=warn` the following warning is printed to the console:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by bsh.Reflect (file:/home/jodeleit/projects/firstspirit/firstspirit/fs/lib/bsh-2.1.8.jar) to method sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream()
WARNING: Please consider reporting this to the maintainers of bsh.Reflect
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

At a first glance the resolving code should be changed to resolve to "open" methods and fields, which can be tested with [`boolean AccessibleObject.canAccess(Object)`](https://docs.oracle.com/javase/9/docs/api/java/lang/reflect/AccessibleObject.html#canAccess-java.lang.Object-). Since this call requires an instance of the declaring class this seems to be bigger rewrite (the instance is currently not provided in the resolving call chain). Perhaps it would be easier to use [`boolean trySetAccessible()`](https://docs.oracle.com/javase/9/docs/api/java/lang/reflect/AccessibleObject.html#trySetAccessible--), even so I do not like that this causes a 'side effect'.

Keywords: Java-9 Java9 JDK9

**Comment by pejobo** [comment]
See https://github.com/pejobo/beanshell2/commit/e9d5f6b5317dc49a63ba5363621fe6eac5f5dadd for a version which make use of "trySetAccessible", that was the easiest way to integrate it.
Method-resolving code needs a big rewrite!

**Comment by nickl-** [comment]
I believe the  [merge-fork-beanshell2](https://github.com/beanshell/beanshell/tree/merge-fork-beanshell2) branch is `<jdkVersion>1.8</jdkVersion>`

**Comment by nickl-** [comment]
complete: see beanshell/beanshell@b977eee running with  --illegal-access=deny Java 9 and/or 10
