### ISSUE TITLE
Starting to define a method crashes beanshell

### ISSUE THREAD

**Issue by voltagex** [beanshell/beanshell#61]
```
Exception in thread "Thread-3" bsh.Parser$LookaheadSuccess
	at bsh.Parser.<init>(Parser.java:5981)
	at bsh.Interpreter.<init>(Interpreter.java:181)
	at bsh.Interpreter.<init>(Interpreter.java:221)
	at bsh.Interpreter.<init>(Interpreter.java:236)
	at bsh.Interpreter.<init>(Interpreter.java:247)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at bsh.Reflect.constructObject(Reflect.java:621)
	at bsh.BSHAllocationExpression.constructObject(BSHAllocationExpression.java:117)
	at bsh.BSHAllocationExpression.objectAllocation(BSHAllocationExpression.java:108)
	at bsh.BSHAllocationExpression.eval(BSHAllocationExpression.java:56)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41)
	at bsh.BSHAssignment.eval(BSHAssignment.java:71)
	at bsh.BSHBlock.evalBlock(BSHBlock.java:125)
	at bsh.BSHBlock.eval(BSHBlock.java:75)
	at bsh.BshMethod.invokeImpl(BshMethod.java:356)
	at bsh.BshMethod.invoke(BshMethod.java:252)
	at bsh.BshMethod.invoke(BshMethod.java:180)
	at bsh.Name.invokeLocalMethod(Name.java:952)
	at bsh.Name.invokeMethod(Name.java:798)
	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:69)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41)
	at bsh.BSHAssignment.eval(BSHAssignment.java:71)
	at bsh.BSHBlock.evalBlock(BSHBlock.java:125)
	at bsh.BSHBlock.eval(BSHBlock.java:75)
	at bsh.BshMethod.invokeImpl(BshMethod.java:356)
	at bsh.BshMethod.invoke(BshMethod.java:252)
	at bsh.BshMethod.invoke(BshMethod.java:180)
	at bsh.Name.invokeLocalMethod(Name.java:952)
	at bsh.Name.invokeMethod(Name.java:798)
	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:69)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41)
	at bsh.Interpreter.eval(Interpreter.java:659)
	at bsh.Interpreter.eval(Interpreter.java:750)
	at bsh.Interpreter.eval(Interpreter.java:739)
	at bsh.Console.main(Console.java:47)
```

Trying to run

`public static ArrayList<String> getConnectedDevicesMac()`

i.e. the start of a method, seems to crash beanshell. It's tricky to debug - I can't actually work out what the exception is.

Also reported at https://github.com/jasonwyatt/Android-DebugPort/issues/18 but this seems to be an issue with beanshell itself.

**Comment by stefanofornari** [comment]
Hello,

generics are not supported yet in beanshell...

Hope this helps,

Ste

**Comment by voltagex** [comment]
@stefanofornari Thanks, but surely it'd be better to display an error than crash the interpreter, right?

**Comment by stefanofornari** [comment]
Yes :)


Ste

**Comment by nickl-** [comment]
Have you tried the  [merge-fork-beanshell2](https://github.com/beanshell/beanshell/tree/merge-fork-beanshell2) branch? Still WIP but many issues are resolved there.

**Comment by nickl-** [comment]
generics now supported see #66
