### ISSUE TITLE
Parameter/variable name lookup confusion

### ISSUE THREAD

**Issue by opeongo** [beanshell/beanshell#659]
As I was putting together a test script for #655 I noticed a problem with parameter/variable name lookups.  The following script fails at line 23 with the error message:
 Attempt to resolve method: add() on undefined variable or class name: c.ylds : at Line: 23 

```java
test1(String c) {  //change String c to String d and it works!
   return this;
}

container() {
   System.err.println("allocate container");
   ylds = new ArrayList();
   work() {
      System.err.println("working");
   }
   return this;
}

c = null;
for (int i=0; i<2; i++) {
   for (int j=0; j<10; j++) {
      if (j%5 == 0) {
         if (c != null) {
            c.work();
         }
         c = container();
      }
      c.ylds.add(test1("hello"));  // line 23
   }
}
```

However, if I change the formal parameter name in the `test1` method from `c` to `d` the script will work successfully.

What am I missing here?

**Comment by nickl-** [comment]
The script calls line 23 every iteration but only ` c = container();` on the 5th. So `c.ylds` is undefined for 0 to 4.

The parameter name of the `test1` method should have no effect.

**Comment by opeongo** [comment]
Your mental interpreter did not execute this correctly.  If you try running it you will see that the container is created when `j == 0` (`0%5 == 0` by the way).  If `c` was null there would have been a different error.

I agree that the name of the parameter to the `test1` method should not have any effect,  But in this test case it appears to do so,  which indicates some kind of lookup mistake.

**Comment by opeongo** [comment]
Here is a revised minimal test script that isolates the problem a bit better.  No loops, no if's to distract the focus.

```java
test1(String c) {  // Change String c to String d and it works
   return this;
}

container() {
   System.err.println("allocate container");
   ylds = new ArrayList();
   return this;
}

Object c = null;
{
   {
      c = container();
   }
   // c = container();  // uncomment this line and it works correctly
   c.ylds.add(test1("hello"));  // Line 17, Error here.  Comment out and it will work
}
c.ylds.add(test1("hello"));  // Line 19, This works
```
Something happens when allocations are made within block namespaces.  Note that as the comments state that this script can be modified to work correctly by either

1. renaming the parameter to the `test1` method, or
2. instantiating the container object outside of the inner block, or
3. Commenting out line 17, and the script will succeed at line 19.

You don't have to change more than one condition.  Any of these three changes independently will avoid the error.

Of course this is a a toy problem and you could just say "get rid of the blocks, you don't need them, that will fix your problem".  True, but think of them as placeholders for more complex structures (such as loops and conditionals) that are commonly required for everyday tasks.

**Comment by nickl-** [comment]
Can reproduce:

```java
allocate container
// Error: Evaluation Error: Attempt to resolve method: add() on undefined variable or class name: c.ylds : at Line: 18 : in file: <unknown file> : c .ylds .add ( test1 ( "hello" ) )

Called from method: global/BlockNameSpace : at Line: 18 : in file: <unknown file> : test1 ( "hello" )
```

**Comment by nickl-** [comment]
Parent #660

**Comment by opeongo** [comment]
There is still a problem here that is failing in my real world test.  I have tried to make some test cases unfortunately I cannot seem to make one to reproduce the problem.  I suspect it has something to do with caching and the isMethod flag.

**Comment by opeongo** [comment]
So I see that when a new BlockNameSpace is created for the first time the [isMethod value from the parent is propogated](https://github.com/beanshell/beanshell/blob/270dd71ab97ce20096275294504f40b43ed1a5a7/src/main/java/bsh/BlockNameSpace.java#L112).

Is this something that needs to also be checked when recycling a BlockNameSpace object from the cache?

**Comment by opeongo** [comment]
Here is an example of the types of errors that I am getting:

```
bsh.EvalError: Sourced file: referenceCacheStressTest.bsh : Error in method invocation: Static method toString(String) not found in class'java.lang.Integer' : at Line: 1126 : in file: referenceCacheStressTest.bsh : Integer .toString ( standId ) 
```
Quite obviously something is going wrong with the cache.

I am trying to pare down this stress test to something that I can post, but it is still a bit large and requires some bit data sets.

**Comment by opeongo** [comment]
@nickl- Ok, I was able to isolate the problem that I am having and reduce it in to a small test case:

```java
Object closure1() {
   list = new ArrayList();

   return this;
}

double doesntMatter() {
    return 1;
}

try {
    t = closure1();
    System.err.println(t.list.size());
} catch (Exception ex) {
    ex.printStackTrace();
}
```

Running the above script results in:
```
beanshell>java -cp target\bsh-3.0.0-SNAPSHOT.jar bsh.Interpreter longRuntest.bsh
Evaluation Error: bsh.EvalError: Sourced file: longRuntest.bsh : Attempt to resolve method: size() on undefined variable or class name: t.list : at Line: 14 : in file: longRuntest.bsh : t .list .size ( )
```

I don't have an explanation and I would be only guessing to try to provide one.

**Comment by nickl-** [comment]
How do you eat an elephant?

**Comment by opeongo** [comment]
Also, if you have a step after the parse to go through the AST you can do interesting things like constant folding, dead code elimination and semantic analysis.  It looks like semantic analysis will be required for the lambda implementation, but it is also useful for checking things like `if (1 == "abcd")` which is a code smell worth warning about.  Since this can be done during parse there is no runtime penalty.  This would also be the place to take care of the actions that are in the `insureParsed()` methods and deal with those concerns during declaration rather than runtime.

**Comment by opeongo** [comment]
Just to add some more clarity, the `doesLeakNamespace()` method would be an abstract method in `SimpleNode`.  Each specialized class would have it's own implementation that mostly would return true **_if any of it's children return true_**, and false otherwise.  Only the BSHReturnStatement class would actually check for leakage using [the type of logic that you already added to BSHMethodDeclaration](https://github.com/beanshell/beanshell/blob/84550d0ae7f1a7c79c9f0942609d7970cb807edb/src/main/java/bsh/BSHMethodDeclaration.java#L79).

**Comment by nickl-** [comment]
You eat an elephant byte for byte. We will get through this elephant too...

Thanx for the ideas, will need pondering before I remark.

**Comment by nickl-** [comment]
Ok so after pondering the suggestions I opted to make the block name space cache optional. Using a Boolean type for the override name space flag it can define 3 states:

1. true we do not swap any name space and override the current top while processing the block
2. false we swap the top name space from callstack with a new block name space instance 
3. null we swap the top name space from callstack with a reusable unique cached block name space instance

The cached name space was then only implemented for the loops, for, for enhanced, and while, as they are the ones reaping most of the benefit since the same block definitely gets processed multiple times. They also have closed scope so no need to worry about anything else needing or reusing the block name space. 

If we find any other blocks that might benefit from a cache strategy we can implement it for them on a case by case basis.

For the loops doing 100000 repetitions there is a 500% performance improvement using the cache compared to going without.

**Comment by nickl-** [comment]
However even though we are now creating new block name space instances uncached for all the blocks in the example at: https://github.com/beanshell/beanshell/issues/659#issuecomment-1369988108 it still doesn't work.

**Comment by nickl-** [comment]
A simpler example:
```java
closure() {
    list = new ArrayList();
    return this.list;
}
t = closure();
--> $0 = [] :List
{ t = closure(); }
// Error: Evaluation Error: illegal void assignment : at Line: 35 : in file: <unknown file> : t = closure ( )
```
Calling the method from a block it apparently looses its `this` context.

**Comment by nickl-** [comment]
Ok now I am confused:

```java
BeanShell 3.0.0-SNAPSHOT.3926
closure() {
    list = new ArrayList();
    return this;
}
--> void
{ t = closure(); print(t.list.size()); }
0I :int
--> void
```

**Comment by nickl-** [comment]
Some more oddities with the doesn't matter method:

```
BeanShell 3.0.0-SNAPSHOT.3926
closure() {
list = new ArrayList();
return this;
}
--> void
{ t = closure(); print(t.list); }
[] :List
--> void
doesntMatter() { return 1; }
--> void
{ t = closure(); print(t.list); }
// Error: Evaluation Error: Undefined argument: t .list  : at Line: 7 : in file: <unknown file> : ( t .list )

doesntMatter() { return this; }
--> void
{ t = closure(); print(t.list); }
[] :List
--> void
```

It does matter if it returns this =)

**Comment by nickl-** [comment]
The doesntMatter bug is also resolved now: 

https://github.com/beanshell/beanshell/blob/7a5f87834cc692ebfa13251c7c62cfbf2ae833ad/src/test/resources/test-scripts/scripted_object2.bsh#L6-L44

**Comment by nickl-** [comment]
Closed: all reported issues are now resolved...until further notice

**Comment by opeongo** [comment]
The problem still exists.  I have a somewhat complicated script, but here is where the failure occurs:
```java
   for (int i=0; i<4; i++) {
      if (i>=4)                             // <----- this is line 386
         System.err.println("i="+i);   
```

Here is the error message that I get:
```
Caused by: Sourced file: unpack.bsh : illegal use of undefined variable, class, or 'void' literal : at Line: 386 : in file: unpack.bsh : ) System .err .println ( "i=" + i ) ;

Caused by: illegal use of undefined variable, class, or 'void' literal
```

I will try to reduce this to a test script, but it does seem a bit random in that unchanged script will fail in different places on successive runs.

**Comment by opeongo** [comment]
I spent the past few days trying to crack this nut, but with no success.  I instrumented the code, followed traces, etc, but I cannot seem to figure out what is going wrong. 

I tried an experiment and commented out the [call to get recycled namespaces from the reference cache in BSHBLock](https://github.com/beanshell/beanshell/blob/47cbe833b7709fe0c5b6c67ee51b731746a7bfe5/src/main/java/bsh/BSHBlock.java#L114).  Previously it looked like:
```java
        if ( null == overrideNamespace )
            enclosingNameSpace = callstack.swap(
                BlockNameSpace.getInstance(callstack.top(), blockId));
        else if ( !overrideNamespace )
            enclosingNameSpace = callstack.swap(
                new BlockNameSpace(callstack.top(), blockId));
        else enclosingNameSpace = null;
```
and I changed it to 
```java
        if ( null == overrideNamespace || !overrideNamespace )
            enclosingNameSpace = callstack.swap(
                new BlockNameSpace(callstack.top(), blockId));
        else enclosingNameSpace = null;
```
This mostly gets rid of the recycled namespaces (they are still in use in enhanced for loops).  After making the change the error about disappearing variables went away.

I cannot explain what is going on, but at least there is a smoking gun.

If you have any suggestions on what to look for I can try again.

**Comment by opeongo** [comment]
I have a reproducible test case that demonstrates a symptom.  I don't know if this is the root of the problem but it seems like it might be related.

I tried running the bshdoc tool [bshdoc.bsh.txt](https://github.com/beanshell/beanshell/files/10865689/bshdoc.bsh.txt)  and got the following error:

```
beanshell>java -cp target\bsh-3.0.0-SNAPSHOT.jar bsh.Interpreter scripts\bshdoc.bsh src\main\resources\bsh\commands\addClassPath.bsh
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bshcommands.xsl"?>
<!-- This file was auto-generated by the bshdoc.bsh script -->
<BshDoc>
 <?xml version="1.0" encoding="UTF-8"?>
 <?xml-stylesheet type="text/xsl" href="bshcommands.xsl"?>
 <!-- This file was auto-generated by the bshdoc.bsh script -->
 <BshDoc>
Evaluation Error: bsh.EvalError: Sourced file: beanshell\scripts\bshdoc.bsh : illegal use of undefined variable, class, or 'void' literal : at Line: 157 : in file: beanshell\scripts\bshdoc.bsh : ;

Called from method: bshdoc/BlockNameSpace13 : at Line: 159 : in file: beanshell\scripts\bshdoc.bsh : bshdoc ( filenames [ i ] )
Called from method: bshdoc/BlockNameSpace13/BlockNameSpace15 : at Line: 173 : in file: beanshell\scripts\bshdoc.bsh : bshdoc ( list )
```

The coding style in this file is out of date, but I am not sure why the error occurs.

**Comment by opeongo** [comment]
I reduced the above problem down to a simple reproducible example and opened a new issue #731.

**Comment by nickl-** [comment]
> ```java
>         if ( null == overrideNamespace || !overrideNamespace )
>             enclosingNameSpace = callstack.swap(
>                 new BlockNameSpace(callstack.top(), blockId));
>         else enclosingNameSpace = null;
> ```
> 
> This mostly gets rid of the recycled namespaces (they are still in use in enhanced for loops). After making the change the error about disappearing variables went away.

Nope this looks like it gets rid of them completely. Doesn't the loops pass null for exactly this reason?

**Comment by nickl-** [comment]
> l : at Line: 386 : in file: unpack.bsh : ) System .err .println ( "i=" + i ) ;

This is strange, if it was another variable it may make sense but I am sure we update `i` on every run so why would it go missing? weird!!

**Comment by nickl-** [comment]
> I reduced the above problem down to a simple reproducible example and opened a new issue #731.

That is very good news indeed!!! Wheeee \o/

**Comment by opeongo** [comment]
Here is an interesting traceback:

```
	at bsh.Interpreter.eval(Interpreter.java:759)
	at bsh.Interpreter.source(Interpreter.java:614)
	at bsh.Interpreter.source(Interpreter.java:628)
	at bsh.Interpreter.source(Interpreter.java:655)
	... 9 more
Caused by: java.lang.NullPointerException: Cannot read field "used" because "ns" is null
	at bsh.BlockNameSpace.getInstance(BlockNameSpace.java:95)
	at bsh.BSHBlock.evalBlock(BSHBlock.java:116)
	at bsh.BSHBlock.eval(BSHBlock.java:105)
	at bsh.BSHForStatement.eval(BSHForStatement.java:83)
	at bsh.BSHBlock.evalBlock(BSHBlock.java:161)
	at bsh.BSHBlock.eval(BSHBlock.java:105)
	at bsh.BshMethod.invokeImpl(BshMethod.java:470)
	at bsh.BshMethod.invoke(BshMethod.java:314)
```

The code [at the point of error](https://github.com/beanshell/beanshell/blob/5e54a86566ff81e20af75cb221d534ba956a7709/src/main/java/bsh/BlockNameSpace.java#L95) is 
```java
    public static NameSpace getInstance(NameSpace parent, int blockId ) {
        BlockNameSpace ns = (BlockNameSpace) blockspaces.get(
                new UniqueBlock(parent, blockId));
        if (1 < ns.used.getAndIncrement()) ns.clear();   // Line 95
        return ns;
    }
```
I can't see an obvious reason for `ns` to be null, because the reference cache is supposed to return a new object if either

1. there is no matching key in the cache, or
2. the value returned for the key is null.

But always `blockspaces.get()` should return a NameSpace, right?  And the fact that it returned null in this case seems to point at a ReferenceCache problem.

The reference monitor queue is running in a separate thread and may have reaped the the reference entry just as it was being retrieved.   Or maybe the key was retrieved in the program thread and the gc thread kicked in and cleared the value just before the entry was dereferenced.   Or perhaps it was related to the lazy instantiation.  There are a few complicated interactions here and possibly a window where it is not protected from concurrent operations.

Maybe this is at the root of the problems that I have been seeing with variables disappearing during long running scripts.  Perhaps the timings lined up that a reference unexpectedly got cleared out of sequence.  They seemed like non-deterministic (timing-based) errors.

Hitting this error is a rare thing.  If it is happening in the ReferenceCache and it is related to concurrent operations then it will be very hard (impossible?) to write a reproducible test case.

Any suggestions on where to look or how to test?

**Comment by opeongo** [comment]
I spent a bit more time looking at the implementation of ReferenceCache and how it is used to cache BlockNameSpace objects, and I found a few problems.

The first obvious one is that the blockspaces cache is declared with weak keys and weak values.  But in the call to [`BlockNameSpace.getInstance()`](https://github.com/beanshell/beanshell/blob/5e54a86566ff81e20af75cb221d534ba956a7709/src/main/java/bsh/BlockNameSpace.java#LL94C1-L94C1) the key that is passed in is quickly discarded, meaning that the entry is immediately eligible to be cleared as soon as the method returns and and the transient key goes out of scope.  So at worst these entries will only be around for one usage before they are gc'ed away, and this defeats the whole purpose of this cache.  The fix for this would be to use a hard reference for the key, but I don't think that's the end of it.

The next one is due to the fact that the values are held in the cache as weak references and don't get a chance to be bound to a hard reference until after `BlockNameSpace.getInstance()` returns.  For it's natal lifespan within the `ReferenceCache.get()`method it is weakly held and subject to clearing by the gc.  Here is the flow: The [`ReferenceCache.get()` calls the `init()` method](https://github.com/beanshell/beanshell/blob/5e54a86566ff81e20af75cb221d534ba956a7709/src/main/java/bsh/util/ReferenceCache.java#L93) to start the initialization of the `BlockNameSpace` object in the cache.  To make this happen asynchronously a[ task object is created and set as the weak reference value in the cache and is also submitted as a hard reference to the executor](https://github.com/beanshell/beanshell/blob/5e54a86566ff81e20af75cb221d534ba956a7709/src/main/java/bsh/util/ReferenceCache.java#LL113C1-L114C1).   The continuation of the `get` method will wait for the executor to finish.  As soon as the executor finishes running it will release its hard reference to the task object.  The only remain reference to the task object is the weak value reference, making the reference immediately eligible to be cleared by the gc.  Before the [`cache.get()`](https://github.com/beanshell/beanshell/blob/5e54a86566ff81e20af75cb221d534ba956a7709/src/main/java/bsh/util/ReferenceCache.java#L94) completes there is a brief window where the gc could have erased the value reference, and that is a likely explanation of what happened in the traceback shown up above.

I cannot see an easy way to alter this ReferenceCache scheme to make it fully reliable.  Running the executor task in one thread and then retrieving the result in the other thread leaves a tiny window of time when there are no hard references to the newly allocated BlockNameSpace, so there will always be a risk of the value reference being cleared and the `BlockNameSpace.getInstance` method returning a null.  And the Executor really doesn't help here with the BlockNameSpace cache, because the main thread will always be waiting at the `cache.get()` for the executor to complete.  It is serialized multi-threading:  extra overhead and negative benefit.


Besides these issues there are a few others that I mentioned previously.  Value references are enqueued to the `ReferenceQueueMonitor` but they don't have a specialized `clear()` method to remove the entries from the cache, so dead entries will build up over time and waste memory.  Also it looks like there is potential for a race in the `get()` method.

Is there a strong reason to be storing the BlockNameSpace objects in a map by namespace and sequence count?  Aren't BlockNameSpace objects substitutable because they are being fully cleared before reuse?   What state do they contain that cannot easily and cheaply be restored (`parent`, `name`)?  If you really want to recycle these objects then I suggest a simpler structure like a stack that has lower overheads, lower complexity, and is easier to reason about.

**Comment by opeongo** [comment]
Also, the `UniqueBlock` class needs to override the `equals` method, otherwise the default test will only match to the exact same object.  The `equals` method is required to implement logical equality to test if the namespace and id are the same, e.g. 
```java
        @Override
        public boolean equals(Object o) {
            if (o == this)
                return true;
            else if (o instanceof UniqueBlock) {
                UniqueBlock ub = (UniqueBlock) o;
                return ns == ub.ns &&
                    id == ub.id;
            } else
                return false;
        }
```

However, it looks like the equality test is overriden in the `ReferenceCache` to be:
```java
        public boolean equals(final Object obj) {
            return hashCode == obj.hashCode();
        }
```

The hashcode calculation is:
```java
            hashCode = key.hashCode() + key.toString().chars().sum();
```

This is unsafe because it is possible for two different objects to have the same hash code.  Maybe this is allowing hash collisions and the wrong namespace objects getting retrieved.

**Comment by opeongo** [comment]
Happy day, I think that I found the problem!  I am pretty sure that [it is what I mentioned previously](https://github.com/beanshell/beanshell/issues/659#issuecomment-1570930893) about the equality test being overridden by a weak hashcode comparison, and this was allowing collisions to happen.

I implemented a simpler weak value reference hashmap and it repeatedly runs successfully on my long running test cases.  Of course with intermittent non-deterministic bugs it is hard to conclusively say that the bug has been squashed, but I am feeling pretty confident because

1. there is a rational explanation of where the error was coming from; and
2. the test have run to completion several times in a row, where previously it was never able to finish.

I will clean up my code and post a PR when I get a chance.

**Comment by opeongo** [comment]
I also had a look at the MemberCache implementation that uses the ReferenceCache and it also has a few problems.

The MemberCache uses class references as keys.  In normal practice the class references will not be collected by the gc unless the ClassLoader that they come from is also gc'ed.  This means that for most situations the soft references on the keys will never be cleared.  It is possible under memory pressure for the soft value references to the MemberCache objects to be gc'ed and cleared, but entries in the map will never be removed because the overridden `clear` method in the value reference doesn't do anything.  Entries in the cache map will just build up, so this is a memory leak problem.

Also, it looks like that the Executor is not fully effective at parallelizing the instantiation of the MemberCache values.  The issue shows up in the [MemberCache constructor](https://github.com/beanshell/beanshell/blob/5e54a86566ff81e20af75cb221d534ba956a7709/src/main/java/bsh/BshClassManager.java#LL115C1-L139C1):
```java
        public MemberCache(Class<?> clazz) {
            Class<?> type = clazz;
            while (type != null) {
                if (isPackageAccessible(type)
                    && ((isPackageScope(type) && !isPrivate(type))
                        || isPublic(type) || haveAccessibility())) {
                    for (Field f : type.getDeclaredFields())
                        if (isPublic(f) || haveAccessibility())
                            cacheMember(Invocable.get(f));
                    for (Method m : type.getDeclaredMethods())
                        if (isPublic(m) || haveAccessibility())
                            if (clazz == type) cacheMember(Invocable.get(m));
                            else cacheMember(memberCache.get(type)               // line 127
                            .findMethod(m.getName(), m.getParameterTypes()));
                    for (Constructor<?> c: type.getDeclaredConstructors())
                        if (clazz == type) cacheMember(Invocable.get(c));
                        else cacheMember(memberCache.get(type)                     // line 131
                            .findMethod(c.getName(), c.getParameterTypes()));
                }
                processInterfaces(type.getInterfaces());
                type = type.getSuperclass();
                memberCache.init(type);                          // line 136
            }
        }

```
I instrumented the code to see how often the main thread had to pause while waiting for the executor task to finish.  The `init` method is called at line 136 and it submits the task to the executor.  The loop continues and at lines 127 and 131 the `get` method is called and retrieves the value of the previously created future.  In all of the tests the thread pauses at lines 127 or 131 the majority of the time waiting for the executor thread to complete the future task.  So this ends up being serialized multi-threading where the one thread is simply waiting for the other thread to complete the action.  It is probably not worth the overhead of the context switches involved. 

There is also the potential for the reference to get cleared in the gap between the executor completing the task and the get method returning the value, just like in the blockSpaces cache.  This is a little bit less likely because the soft references require memory pressure, but there is a clear risk of returning a null.  This is a problem that I cannot see fixing easily.

I suggest to not use the ReferenceCache class for MemberCache objects and instead use something simpler like the value reference cache that I added in PR #741.

**Comment by nickl-** [comment]
> I suggest to not use the ReferenceCache class for MemberCache objects and instead use something simpler like the value reference cache that I added in PR https://github.com/beanshell/beanshell/pull/741.

What maintains this cache, when are entries removed? I don't see anywhere that we remove cached entries does this not cause a memory leak then?

**Comment by nickl-** [comment]
> Here is an interesting traceback:
> 
> ```
> 	at bsh.Interpreter.eval(Interpreter.java:759)
> 	at bsh.Interpreter.source(Interpreter.java:614)
> 	at bsh.Interpreter.source(Interpreter.java:628)
> 	at bsh.Interpreter.source(Interpreter.java:655)
> 	... 9 more
> Caused by: java.lang.NullPointerException: Cannot read field "used" because "ns" is null
> 	at bsh.BlockNameSpace.getInstance(BlockNameSpace.java:95)
> 	at bsh.BSHBlock.evalBlock(BSHBlock.java:116)
> 	at bsh.BSHBlock.eval(BSHBlock.java:105)
> 	at bsh.BSHForStatement.eval(BSHForStatement.java:83)
> 	at bsh.BSHBlock.evalBlock(BSHBlock.java:161)
> 	at bsh.BSHBlock.eval(BSHBlock.java:105)
> 	at bsh.BshMethod.invokeImpl(BshMethod.java:470)
> 	at bsh.BshMethod.invoke(BshMethod.java:314)
> ```
> 
> The code [at the point of error](https://github.com/beanshell/beanshell/blob/5e54a86566ff81e20af75cb221d534ba956a7709/src/main/java/bsh/BlockNameSpace.java#L95) is
> 
> ```java
>     public static NameSpace getInstance(NameSpace parent, int blockId ) {
>         BlockNameSpace ns = (BlockNameSpace) blockspaces.get(
>                 new UniqueBlock(parent, blockId));
>         if (1 < ns.used.getAndIncrement()) ns.clear();   // Line 95
>         return ns;
>     }
> ```
> 
> I can't see an obvious reason for `ns` to be null, because the reference cache is supposed to return a new object if either
> 
>     1. there is no matching key in the cache, or
> 
>     2. the value returned for the key is null.
> 
> 
> But always `blockspaces.get()` should return a NameSpace, right? And the fact that it returned null in this case seems to point at a ReferenceCache problem.
> 
> The reference monitor queue is running in a separate thread and may have reaped the the reference entry just as it was being retrieved. Or maybe the key was retrieved in the program thread and the gc thread kicked in and cleared the value just before the entry was dereferenced. Or perhaps it was related to the lazy instantiation. There are a few complicated interactions here and possibly a window where it is not protected from concurrent operations.
> 
> Maybe this is at the root of the problems that I have been seeing with variables disappearing during long running scripts. Perhaps the timings lined up that a reference unexpectedly got cleared out of sequence. They seemed like non-deterministic (timing-based) errors.
> 
> Hitting this error is a rare thing. If it is happening in the ReferenceCache and it is related to concurrent operations then it will be very hard (impossible?) to write a reproducible test case.
> 
> Any suggestions on where to look or how to test?

What happens if we synchronize the `getInstance` method, or alternatively the `get` method on the `ReferenceCache`? That way it should lock execution until we are done with the `ns`.

**Comment by nickl-** [comment]
> The MemberCache uses class references as keys. In normal practice the class references will not be collected by the gc unless the ClassLoader that they come from is also gc'ed. This means that for most situations the soft references on the keys will never be cleared. It is possible under memory pressure for the soft value references to the MemberCache objects to be gc'ed and cleared, but entries in the map will never be removed because the overridden clear method in the value reference doesn't do anything. Entries in the cache map will just build up, so this is a memory leak problem.

The logic here is sound, what if we use the class name string instead?

**Comment by opeongo** [comment]
> > I suggest to not use the ReferenceCache class for MemberCache objects and instead use something simpler like the value reference cache that I added in PR #741.
> 
> What maintains this cache, when are entries removed? I don't see anywhere that we remove cached entries does this not cause a memory leak then?

The clean() method is called periodically to purge the ReferenceQueue.  See here:
https://github.com/beanshell/beanshell/blob/5a3fb213ec4782df47975c8d7455f6d66f1b3da8/src/main/java/bsh/util/ValueReferenceMap.java#L77-L85

**Comment by opeongo** [comment]
> What happens if we synchronize the `getInstance` method, or alternatively the `get` method on the `ReferenceCache`? That way it should lock execution until we are done with the `ns`.

It is not a synchronization issue, or rather that because access is synchronized this is exactly the source to the issue.  There is a gap during execution between when one thread has a hard reference to the object, but it completes and returns, letting go of the reference.  Then the other thread continues and tries to get access to the object from the cache.  During the gap between when one thread stops and the other resumes no one is holding a reference and there is a chance for the GC to clear the reference.  This multi-threaded design is not fixable.

Also it appears as though the multi-threading is mostly serialized anyway, so it is not achieving much of a  performance boost.

**Comment by opeongo** [comment]
> The logic here is sound, what if we use the class name string instead?

Really what you want to have are hard references on the keys.  What is the point of having weak references for objects that you are not holding on to, they would be eligible for immediate clearing so whats the point?  So if you use a weak reference to an unheld string instead then it just makes a different problem.  And I suppose if the string was interned in to the internal jvm string pool (due to something that the jvm was doing) then they would also never get cleared.

However, the keys in the ReferenceCache are class object references, so they are likely to always have a hard reference from the ClassLoader.  So the keys will never be cleared and the clear() method on the keys will never get called. 

The cache values have weak references and if unused they will get cleared when the GC decides to.  When they get cleared the weak reference object is cleared.  However nothing is in place to remove the entry from the cache when the values are cleared.  The key is still there and it points to a weak reference that has been cleared.   Entries in the cache map that have hard references on the keys will never go away, unless an explicit action is taken when the value reference is cleared.  I have looked at the code and I don't see it happening.

Have a look at the replacement code that I wrote.  It is single threaded, simpler, and doesn't have the same issues.

**Comment by jimjag** [comment]
Fixed by #789 (which includes #741), merged to master in c8aac59d.

The root cause was the old `ReferenceCache` key comparison: two
keys counted as equal whenever their hash codes matched. Block-namespace
keys are hashed from identity hash codes, which differ from run to run,
so a block could occasionally be handed another block's namespace.
#789 replaces it with a map that compares keys exactly.
