### ISSUE TITLE
NoClassDefFoundError on enums

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#662]
Tried the enum example from [w3schools](https://www.w3schools.com/java/java_enums.asp) but get a null pointer exception.

All current enum tests pass so what is the difference?

If I change the enum name from Level to Status for example it works as expected.

```java
bsh % enum Status {HIGH, MEDIUM, LOW};
--> $0 = class Status :Class
bsh % Status.values();
--> $1 = {HIGH, MEDIUM, LOW} :Status[]
bsh % enum Level {HIGH, MEDIUM, LOW};
--> $2 = class Level :Class
bsh % Level.values();
// Error: Unknown error: java.lang.NullPointerException: Cannot invoke "bsh.BshClassManager$MemberCache.findMethod(String, java.lang.Class[])" because the return value of "bsh.util.ReferenceCache.get(Object)" is null
```

Testing several different names, some work and others don't, can't see any pattern.

**Comment by nickl-** [comment]
After fixing Reference cache obscuring errors ff28429 we now get: 

```java
bsh % enum Level {HIGH, MEDIUM, LOW};
--> $0 = class Level :Class
bsh % Level.values();
// Error: Unknown error: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: eve
```

**Comment by nickl-** [comment]
It is extremely odd:
```java
Level.class;
--> $8 = class Level :Class
Level.class.getClasses();
--> $9 = {class java.lang.Enum$EnumDesc} :Class[]
Level.class.isEnum();
--> $0 = true :boolean
Level.class.toGenericString();
--> $1 = "public final enum Level" :String
Level.class.getFields();
// Error: Target Exception: Method Invocation getFields : at Line: 92 : in file: <unknown file> : .getFields ( ) 
Caused by: java.lang.NoClassDefFoundError: eve
java.lang.ClassNotFoundException: eve
at java.base/java.lang.Class.getDeclaredFields0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3329)
at java.base/java.lang.Class.privateGetPublicFields(Class.java:3356)
at java.base/java.lang.Class.getFields(Class.java:1960)
at bsh.Invocable.invokeTarget(Invocable.java:209)
at bsh.Invocable.invoke(Invocable.java:223)
at bsh.Reflect.invokeObjectMethod(Reflect.java:105)
at bsh.BSHPrimarySuffix.doName(BSHPrimarySuffix.java:184)
at bsh.BSHPrimarySuffix.doSuffix(BSHPrimarySuffix.java:114)
at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:67)
at bsh.BSHAssignment.eval(BSHAssignment.java:40)
at bsh.Interpreter.run(Interpreter.java:509)
at bsh.Interpreter.main(Interpreter.java:452)
Level.class.getMethods();
// Error: Target Exception: Method Invocation getMethods : at Line: 93 : in file: <unknown file> : .getMethods ( )
Caused by: java.lang.NoClassDefFoundError: eve
java.lang.ClassNotFoundException: eve
at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3434)
at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3459)
at java.base/java.lang.Class.getMethods(Class.java:2051)
at bsh.Invocable.invokeTarget(Invocable.java:209)
at bsh.Invocable.invoke(Invocable.java:223)
at bsh.Reflect.invokeObjectMethod(Reflect.java:105)
at bsh.BSHPrimarySuffix.doName(BSHPrimarySuffix.java:184)
at bsh.BSHPrimarySuffix.doSuffix(BSHPrimarySuffix.java:114)
at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:67)
at bsh.BSHAssignment.eval(BSHAssignment.java:40)
at bsh.Interpreter.run(Interpreter.java:509)
at bsh.Interpreter.main(Interpreter.java:452)
```

**Comment by opeongo** [comment]
I just tried it and got
```java
BeanShell 3.0.0-SNAPSHOT.1169
bsh % enum Status {HIGH, MEDIUM, LOW};
--> $0 = class Status :Class
bsh % bsh % Status.values();
--> $1 = {HIGH, MEDIUM, LOW} :Status[]
bsh % enum Level {HIGH, MEDIUM, LOW};
--> $2 = class Level :Class
bsh % bsh % Level.values();
// Error: Unknown error: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: eve
bsh %
```

**Comment by nickl-** [comment]
Turned out it was all enums starting with L

**Comment by opeongo** [comment]
Nice catch
